In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [7]:
data = pd.read_csv("//content//bmw_global_sales_2018_2025.csv", delimiter= ',')
data

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.50,1.00
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.50,1.00
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.50,1.00
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.50,1.00
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.50,1.00
...,...,...,...,...,...,...,...,...,...,...,...
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,0.201,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,0.203,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,0.180,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,0.196,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,0.167,5.89,2.37,1.41

In [8]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3072 entries, 0 to 3071
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              3072 non-null   int64
 1   Month             3072 non-null   int64
 2   Region            3072 non-null   object
 3   Model             3072 non-null   object
 4   Units_Sold        3072 non-null   int64
 5   Avg_Price_EUR     3072 non-null   int64
 6   Revenue_EUR       3072 non-null   int64
 7   BEV_Share         3072 non-null   float64
 8   Premium_Share     3072 non-null   float64
 9   GDP_Growth        3072 non-null   float64
 10  Fuel_Price_Index  3072 non-null   float64
dtypes: float64(4), int64(5), object(2)
memory usage: 264.1+ KB

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [9]:
data.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

In [10]:
data.tail()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,0.201,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,0.203,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,0.180,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,0.196,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,0.167,5.89,2.37,1.41

In [11]:
data.isnull()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
3067,False,False,False,False,False,False,False,False,False,False,False
3068,False,False,False,False,False,False,False,False,False,False,False
3069,False,False,False,False,False,False,False,False,False,False,False
3070,False,False,False,False,False,False,False,False,False,False,False
3071,False,False,False,False,False,False,False,False,False,False,False

In [12]:
data.isnull().sum()

Year                0
Month               0
Region              0
Model               0
Units_Sold          0
Avg_Price_EUR       0
Revenue_EUR         0
BEV_Share           0
Premium_Share       0
GDP_Growth          0
Fuel_Price_Index    0
dtype: int64

In [13]:
data['Model']

0       3 Series
1       5 Series
2             X3
3             X5
4             X7
          ...
3067          X5
3068          X7
3069          i4
3070          iX
3071        MINI
Name: Model, Length: 3072, dtype: object

In [14]:
data.drop_duplicates()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.50,1.00
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.50,1.00
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.50,1.00
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.50,1.00
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.50,1.00
...,...,...,...,...,...,...,...,...,...,...,...
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,0.201,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,0.203,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,0.180,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,0.196,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,0.167,5.89,2.37,1.41

In [15]:
k1= pd.get_dummies(data)
print(k1)

      Year  Month  Units_Sold  Avg_Price_EUR  Revenue_EUR  BEV_Share  \
0     2018      1        7822          47482    371404204      0.011
1     2018      1       10280          61685    634121800      0.019
2     2018      1        3105          58433    181434465      0.022
3     2018      1        7420          67955    504226100      0.021
4     2018      1        8474          92300    782150200      0.035
...    ...    ...         ...            ...          ...        ...
3067  2025     12        9281          68198    632945638      0.201
3068  2025     12       12785          91839   1174161615      0.203
3069  2025     12        4906          63437    311221922      0.180
3070  2025     12        7871          73867    581407157      0.196
3071  2025     12        6732          41811    281471652      0.167

      Premium_Share  GDP_Growth  Fuel_Price_Index  Region_China  ...  \
0             19.12        3.50              1.00         False  ...
1             19.12        3.50              1.00         False  ...
2             19.12        3.50              1.00         False  ...
3             19.12        3.50              1.00         False  ...
4             19.12        3.50              1.00         False  ...
...             ...         ...               ...           ...  ...
3067           5.89        2.37              1.41         False  ...
3068           5.89        2.37              1.41         False  ...
3069           5.89        2.37              1.41         False  ...
3070           5.89        2.37              1.41         False  ...
3071           5.89        2.37              1.41         False  ...

      Region_RestOfWorld  Region_USA  Model_3 Series  Model_5 Series  \
0                  False       False            True           False
1                  False       False           False            True
2                  False       False           False           False
3                  False       False           False           False
4                  False       False           False           False
...                  ...         ...             ...             ...
3067                True       False           False           False
3068                True       False           False           False
3069                True       False           False           False
3070                True       False           False           False
3071                True       False           False           False

      Model_MINI  Model_X3  Model_X5  Model_X7  Model_i4  Model_iX
0          False     False     False     False     False     False
1          False     False     False     False     False     False
2          False      True     False     False     False     False
3          False     False      True     False     False     False
4          False     False     False      True     False     False
...          ...       ...       ...       ...       ...       ...
3067       False     False      True     False     False     False
3068       False     False     False      True     False     False
3069       False     False     False     False      True     False
3070       False     False     False     False     False      True
3071        True     False     False     False     False     False

[3072 rows x 21 columns]

In [16]:
data.pop('BEV_Share')
data

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,19.12,3.50,1.00
1,2018,1,Europe,5 Series,10280,61685,634121800,19.12,3.50,1.00
2,2018,1,Europe,X3,3105,58433,181434465,19.12,3.50,1.00
3,2018,1,Europe,X5,7420,67955,504226100,19.12,3.50,1.00
4,2018,1,Europe,X7,8474,92300,782150200,19.12,3.50,1.00
...,...,...,...,...,...,...,...,...,...,...
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,5.89,2.37,1.41