In [1]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:
import pandas as pd
import numpy as np

In [3]:
s1 = pd.Series([21, 23, 25, '12'])    #Series =column in table

In [4]:
s1    # one dimensional array holding data of any type

0    21
1    23
2    25
3    12
dtype: object

In [5]:
s1 = pd.Series([21, 23, 25, 12.0])
s1

0    21.0
1    23.0
2    25.0
3    12.0
dtype: float64

In [6]:
s2 = pd.Series([23, 45, 67, 12, 34], index=['a', 'b', 'c', 'd','e'], dtype=float)
s2

a    23.0
b    45.0
c    67.0
d    12.0
e    34.0
dtype: float64

In [7]:
s4= pd.Series({'e':65, 'f':23, 'g':31})
s4

e    65
f    23
g    31
dtype: int64

In [8]:
d1= pd.DataFrame([43, 54, 23, 32])
d1

    0
0  43
1  54
2  23
3  32

In [9]:
d2 = pd.DataFrame([[2, 3, 4],[1, 4, 5],[6, 7, 8]])
d2

   0  1  2
0  2  3  4
1  1  4  5
2  6  7  8

In [10]:
d2= pd.DataFrame(s2)
d2

      0
a  23.0
b  45.0
c  67.0
d  12.0
e  34.0

In [11]:
d3 = pd.DataFrame([[2,3,4], [5,6,7], [9,8,6]], columns=['a','b','c'])
d3

   a  b  c
0  2  3  4
1  5  6  7
2  9  8  6

In [12]:
d3 = pd.DataFrame([[2,3,4], [5,6,7], [9,8,6]], columns=['a','b','c'], index=['x','y','z'])
d3

   a  b  c
x  2  3  4
y  5  6  7
z  9  8  6

In [13]:
dic = [{'alex':1,'jeo':2},{'ema':4,'dora':5,'alice':7},{'ema':14,'dora':15,'alice':7}]
pd.DataFrame(dic, index=['a','b','c'])

   alex  jeo   ema  dora  alice
a   1.0  2.0   NaN   NaN    NaN
b   NaN  NaN   4.0   5.0    7.0
c   NaN  NaN  14.0  15.0    7.0

In [14]:
d3

   a  b  c
x  2  3  4
y  5  6  7
z  9  8  6

In [15]:
print(d3['a'])

x    2
y    5
z    9
Name: a, dtype: int64

In [16]:
print(d3['b'])

x    3
y    6
z    8
Name: b, dtype: int64

In [17]:
d3['d']=d3['b']*d3['c']
d3['e']=d3['a']+d3['d']
d3

   a  b  c   d   e
x  2  3  4  12  14
y  5  6  7  42  47
z  9  8  6  48  57

In [18]:
pop = d3.pop('b')
d3

   a  c   d   e
x  2  4  12  14
y  5  7  42  47
z  9  6  48  57

In [19]:
d3.pop('a')
d3

   c   d   e
x  4  12  14
y  7  42  47
z  6  48  57

In [20]:
d3.insert(1, 'new1', d3['c'])   #(loc, col, data)
d3

   c  new1   d   e
x  4     4  12  14
y  7     7  42  47
z  6     6  48  57

In [21]:
d={'c':1,'new1':33,'e':22}
df11=d3._append(d, ignore_index=True)
df11

   c  new1     d   e
0  4     4  12.0  14
1  7     7  42.0  47
2  6     6  48.0  57
3  1    33   NaN  22

In [22]:
import numpy as np
d4 = pd.DataFrame({'abc':np.random.randint(2,6,size=(15)),'cde':np.random.randint(4,8,size=(15)),'efg':np.random.randint(3,10,size=(15))})
d4

    abc  cde  efg
0     2    6    4
1     4    4    5
2     5    5    6
3     2    7    9
4     3    5    4
5     3    5    7
6     4    5    4
7     4    5    6
8     2    7    8
9     5    6    5
10    3    5    5
11    3    6    9
12    2    5    5
13    5    6    3
14    3    7    4

In [23]:
d4.head()   #by using head() we will get the first five rows

   abc  cde  efg
0    2    6    4
1    4    4    5
2    5    5    6
3    2    7    9
4    3    5    4

In [24]:
d4.tail()   #by using tail() we will get the last five rows

    abc  cde  efg
10    3    5    5
11    3    6    9
12    2    5    5
13    5    6    3
14    3    7    4

In [25]:
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     15 non-null     int64
 1   cde     15 non-null     int64
 2   efg     15 non-null     int64
dtypes: int64(3)
memory usage: 492.0 bytes

In [26]:
d4.describe()

             abc        cde        efg
count  15.000000  15.000000  15.000000
mean    3.333333   5.600000   5.600000
std     1.112697   0.910259   1.882248
min     2.000000   4.000000   3.000000
25%     2.500000   5.000000   4.000000
50%     3.000000   5.000000   5.000000
75%     4.000000   6.000000   6.500000
max     5.000000   7.000000   9.000000

In [27]:
d4

    abc  cde  efg
0     2    6    4
1     4    4    5
2     5    5    6
3     2    7    9
4     3    5    4
5     3    5    7
6     4    5    4
7     4    5    6
8     2    7    8
9     5    6    5
10    3    5    5
11    3    6    9
12    2    5    5
13    5    6    3
14    3    7    4

In [28]:
print(d4.loc[9, 'abc'])

5

In [29]:
print(d4.iloc[9,0])

5

In [30]:
d4.iloc[2:7,[0,2]]  #(row index, column index)

   abc  efg
2    5    6
3    2    9
4    3    4
5    3    7
6    4    4

In [31]:
a = [['rk', 102, 15000],['ram', 103, 20000], ['krishna', 104, 25000]]
df1 = pd.DataFrame(a, columns= ['name', 'id', 'salary'])
df1

      name   id  salary
0       rk  102   15000
1      ram  103   20000
2  krishna  104   25000

In [32]:
y = df1[df1.salary>=20000]
print(y)
y[['id', 'salary']]

      name   id  salary
1      ram  103   20000
2  krishna  104   25000

    id  salary
1  103   20000
2  104   25000

In [33]:
df1._append({'name':'aravind','id':105,'salary':30000}, ignore_index=True)

      name   id  salary
0       rk  102   15000
1      ram  103   20000
2  krishna  104   25000
3  aravind  105   30000

In [34]:
df1 = df1._append({'name':np.nan,'id':105,'salary':30000}, ignore_index=True)
df1

      name     id   salary
0       rk  102.0  15000.0
1      ram  103.0  20000.0
2  krishna  104.0  25000.0
3      NaN  105.0  30000.0

In [35]:
#get_dummies() in pandas is used to convert categorical data (text categories) into numeric columns.
#This process is called One-Hot Encoding, which is commonly used in machine learning and data preprocessing.

#Many ML algorithms cannot understand text values like "Male", "Female", "Food", "Travel". So get_dummies() converts them into 0 and 1 columns.

import pandas as pd

data = {
    "firstname": ["Raja", "Anu", "Ravi", "Deepu"],
    "lastname": ["narendra", "rani", "raja", "singh"],
    "employmenttype": ['Service', 'Business', 'Student', 'Service'],
    "country": ['Australia', 'usa', 'sweden', 'india']
}
df = pd.DataFrame(data, columns= ['firstname', 'lastname', 'employmenttype', 'country'])
print(df)

  firstname  lastname employmenttype    country
0      Raja  narendra        Service  Australia
1       Anu      rani       Business        usa
2      Ravi      raja        Student     sweden
3     Deepu     singh        Service      india

In [36]:
df1 = pd.get_dummies(df['employmenttype'], dtype=int)
df2 = pd.get_dummies(df['country'], dtype=int)
print(df1)
print(df2)

   Business  Service  Student
0         0        1        0
1         1        0        0
2         0        0        1
3         0        1        0
   Australia  india  sweden  usa
0          1      0       0    0
1          0      0       0    1
2          0      0       1    0
3          0      1       0    0

In [37]:
df

  firstname  lastname employmenttype    country
0      Raja  narendra        Service  Australia
1       Anu      rani       Business        usa
2      Ravi      raja        Student     sweden
3     Deepu     singh        Service      india

In [38]:
import pandas as pd
india_weather = pd.DataFrame({
    "city" : ['vizag', 'bangalore', 'hyderabad'],
    "temprature" : [40, 29, 37],
    "humidity": [80, 40,60]
})
india_weather

        city  temprature  humidity
0      vizag          40        80
1  bangalore          29        40
2  hyderabad          37        60

In [39]:
import pandas as pd
us_weather = pd.DataFrame({
    "city" : ['new york', 'chicago', 'orlando'],
    "temprature" : [40, 29, 37],
    "humidity": [80, 40,60]
})
us_weather

       city  temprature  humidity
0  new york          40        80
1   chicago          29        40
2   orlando          37        60

In [40]:
df= pd.concat([india_weather, us_weather])
df

        city  temprature  humidity
0      vizag          40        80
1  bangalore          29        40
2  hyderabad          37        60
0   new york          40        80
1    chicago          29        40
2    orlando          37        60

In [41]:
df= pd.concat([india_weather, us_weather], ignore_index=True)
df

        city  temprature  humidity
0      vizag          40        80
1  bangalore          29        40
2  hyderabad          37        60
3   new york          40        80
4    chicago          29        40
5    orlando          37        60

In [42]:
import pandas as pd
emp = {'Name':['raja', 'rana', 'will', 'smith','raja'],
      "Age":[30, 29, 35, 42, 30]}
info=pd.DataFrame(emp)
print(info)
print("---------------------")
info = info.drop_duplicates()
print(info)

    Name  Age
0   raja   30
1   rana   29
2   will   35
3  smith   42
4   raja   30
---------------------
    Name  Age
0   raja   30
1   rana   29
2   will   35
3  smith   42

In [43]:
def calc_sum(kiran):
    return kiran+1
data ={
    "x": [50, 40, 30],
    "y": [300, 1112, 42]
}
df= pd.DataFrame(data)
print(df)
x= df.apply(calc_sum)
print(x)

    x     y
0  50   300
1  40  1112
2  30    42
    x     y
0  51   301
1  41  1113
2  31    43